# Generated by Django 3.2.13 on 2022-07-19 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aud_name', models.CharField(max_length=50, unique=True)),
                ('aud_desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctyp_name', models.CharField(max_length=50, unique=True)),
                ('doctyp_desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_path', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=150, null=True)),
                ('keywords', models.CharField(max_length=250, null=True)),
                ('pub_dt', models.DateField(null=True)),
                ('doc_abs', models.TextField(null=True)),
                ('doc_txt', models.TextField(null=True)),
                ('aud_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.audience')),
                ('doctyp_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.documenttype')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event')),
            ],
        ),
    ]
