# Generated by Django 3.2.13 on 2022-06-30 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aud_name', models.CharField(max_length=50, unique=True)),
                ('aud_desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctyp_name', models.CharField(max_length=50, unique=True)),
                ('doctyp_desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('event_tag', models.CharField(max_length=250)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_location', models.CharField(max_length=150)),
                ('event_venue', models.CharField(max_length=150)),
                ('venue_details', models.TextField()),
                ('venue_location', models.TextField()),
                ('venue_directions', models.TextField()),
                ('accomodations', models.TextField(default='Venue Accomodations')),
                ('active', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_code', models.CharField(max_length=20, unique=True)),
                ('expertise_desc', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Expertise',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=250)),
                ('web_address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=3)),
                ('bio', models.TextField()),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('active', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=3)),
                ('credentials', models.TextField()),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to=None)),
                ('active', models.BooleanField(null=True)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.expertise')),
            ],
        ),
        migrations.CreateModel(
            name='EventOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=250)),
                ('offer_subtitle', models.CharField(max_length=250, null=True)),
                ('offer_details', models.TextField()),
                ('active', models.BooleanField(null=True)),
                ('event', models.ManyToManyField(to='member.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(to='member.Speaker'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(to='member.Sponsor'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_path', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=150, null=True)),
                ('keywords', models.CharField(max_length=250, null=True)),
                ('pub_dt', models.DateField(null=True)),
                ('doc_abs', models.TextField(null=True)),
                ('doc_txt', models.TextField(null=True)),
                ('document', models.FileField(null=True, upload_to=None)),
                ('aud_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.audience')),
                ('doctyp_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.documenttype')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.event')),
            ],
        ),
    ]
