# Generated by Django 3.2.13 on 2022-10-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_document_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_route', models.CharField(max_length=150)),
                ('dr_description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='doc_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.documentroute'),
        ),
    ]
