# Generated by Django 3.2.13 on 2022-06-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20220616_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_abs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_txt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='pub_dt',
            field=models.DateField(null=True),
        ),
    ]
