# Generated by Django 3.2.13 on 2022-10-21 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20221021_1716'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('member', '0004_auto_20221021_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
