# Generated by Django 3.2.13 on 2022-08-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistration',
            old_name='guest_first_name',
            new_name='guest_name',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='guest_last_name',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='guest_email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
