# Generated by Django 3.2.13 on 2022-08-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20220809_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='guest_name',
        ),
        migrations.AlterModelTable(
            name='eventregistration',
            table='eventregistration',
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, null=True)),
                ('guest_email', models.EmailField(max_length=100, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventattendance')),
            ],
            options={
                'db_table': 'marks',
            },
        ),
    ]
