# Generated by Django 3.2.13 on 2022-09-16 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20220816_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, null=True)),
                ('guest_email', models.EmailField(max_length=100, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventattendance')),
            ],
            options={
                'db_table': 'event_guest',
            },
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='attendance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.eventattendance'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.AddField(
            model_name='guest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventregistration'),
        ),
    ]
