# Generated by Django 3.2.13 on 2022-10-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20220916_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='member',
            new_name='event_reg',
        ),
    ]
