# Generated by Django 3.2.13 on 2022-10-11 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_member_guest_event_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event_reg',
        ),
        migrations.AddField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
            preserve_default=False,
        ),
    ]
