# Generated by Django 3.2.13 on 2022-06-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_communication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
