# Generated by Django 3.2.13 on 2022-07-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
