# Generated by Django 3.2.13 on 2022-10-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20221014_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='Transparent-gold.jpg', upload_to='news/'),
        ),
    ]
