# Generated by Django 3.2.13 on 2022-10-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportpartners',
            old_name='url',
            new_name='web_address',
        ),
        migrations.AddField(
            model_name='strategicpartner',
            name='logo',
            field=models.ImageField(default='Transparent-gold.jpg', upload_to='index/'),
        ),
        migrations.AddField(
            model_name='supportpartners',
            name='logo',
            field=models.ImageField(default='Transparent-gold.jpg', upload_to='index'),
        ),
        migrations.AddField(
            model_name='team',
            name='picture',
            field=models.ImageField(default='Transparent-gold.jpg', upload_to='index/'),
        ),
    ]
