# Generated by Django 3.2.13 on 2022-10-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicpartner',
            name='credentials',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='credentials',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
