/*
 This is the CIRSx data ingestion sql that will be run after the implementation

 Adding Countries
 */


 insert into cirsx_dev.public.account_country(country_name)
 values
('United States of America'),
('Afghanistan'),
('Albania'),
('Algeria'),
('Andorra'),
('Angola'),
('Antigua and Barbuda'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bhutan'),
('Bolivia'),
('Bosnia and Herzegovina'),
('Botswana'),
('Brazil'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Cabo Verde'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Central African Republic'),
('Chad'),
('Chile'),
('China'),
('Colombia'),
('Comoros'),
('Congo'),
('Costa Rica'),
('Côte d’Ivoire'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('Djibouti'),
('Dominica'),
('Dominican Republic'),
('East Timor (Timor-Leste)'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Estonia'),
('Eswatini'),
('Ethiopia'),
('Fiji'),
('Finland'),
('France'),
('Gabon'),
('Gambia'),
('Georgia'),
('Germany'),
('Ghana'),
('Greece'),
('Grenada'),
('Guatemala'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Honduras'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland'),
('Israel'),
('Italy'),
('Jamaica'),
('Japan'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('North Korea'),
('South Korea '),
('Kosovo'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Mauritania'),
('Mauritius'),
('Mexico'),
('Federated States of Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Morocco'),
('Mozambique'),
('Myanmar (Burma)'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('North Macedonia'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Qatar'),
('Romania'),
('Russia'),
('Rwanda'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint Vincent and the Grenadines'),
('Samoa'),
('San Marino'),
('Sao Tome and Principe'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('Spain'),
('Sri Lanka'),
('Sudan'),
('South Sudan'),
('Suriname'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Togo'),
('Tonga'),
('Trinidad and Tobago'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('Uruguay'),
('Uzbekistan'),
('Vanuatu'),
('Vatican City'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Zambia'),
('Zimbabwe');


--Adding Event Types

insert into cirsx_dev.public.event_eventtype(event_type)
values
('Conference'),
('Web Conference');


--Adding Events

insert into cirsx_dev.public.event_event(event_name,
                                         event_tag,
                                         event_start_date,
                                         event_end_date,
                                         event_location,
                                         event_venue,
                                         venue_details,
                                         venue_location,
                                         venue_directions,
                                         accomodations,
                                         active,
                                         event_type_id)
values
('2022 CIRSx Annual Conference',
 'Hosted by CIRSx in Partnership with SurvivingMold',
 '04/28/2022',
 '05/01/2022',
 'Ft Lauderdale, FL',
 'Sonesta Fort Lauderdale',
 'The sun. The surf. The soft, sandy beach—all just steps away from the laid-back sophistication of Sonesta Fort ' ||
 'Lauderdale hotel. With sweeping beachside views, unforgettable service and winner of the TripAdvisor Certificate of ' ||
 'Excellence—it’s clear why Sonesta is a preferred destination for meetings and events in Fort Lauderdale Beach.',
 'Sonesta Fort Lauderdale Beach Hotel, 999 N Fort Lauderdale Blvd, Fort Lauderdale, FL ',
 'Located just 5 miles from the Fort Lauderdale-Hollywood International Airport.',
 'You will receive an email with a link to make your hotel reservation at a discounted room rate when you register and pay for the conference.',
 'True',
 1),
('I Dream of GENIE Volume 4',
 'Joint Surviving Mold | CIRSx Web Conference',
 '07/15/2022',
 '',
 'Webinar',
 'www.cirsx.com',
 'Learn about new diagnostics and treatment paradigms for complicated patients with chronic unexplained symptoms and ' ||
 'illnesses. Better understand chronic inflammatory response syndrome CIRS.  Review the latest information about ' ||
 'biofilms and cognitive decline. Explore energy production and the new world of transcriptomics. Examine the newest ' ||
 'understanding of the role of Actinomycetes in environmental landscape. Connect to the premiere community of CIRS ' ||
 'practitioners and environmental experts.',
 'Webinar url will be given once you register.',
 '',
 '“I Dream of GENIE” Volume 4 CME Accreditation Statement
This activity has been planned and implemented in accordance with the accreditation requirements and policies of the ' ||
'New Mexico Medical Society (NMMS) through the joint sponsorship of Rehoboth McKinley Christian Health Care Services ' ||
'(RMCHCS) and Gallup Indian Medical Center. RMCHCS is accredited by the NMMS to provide continuing medical education ' ||
'for physicians.
Credit Statement: RMCHCS designates this live activity for a maximum of 3.5 AMA PRA Category 1 Credit(s)™.
Physicians should claim only the credit commensurate with the extent of their participation in the activity.
All of the relevant financial relationships listed for these individual(s), both planners and speakers, have been ' ||
'mitigated.',
True,
 2)